### ISSUE TITLE
Build artifacts shouldn't be committed to source control

### ISSUE THREAD

**Issue by Daniel15** [reactjs/prop-types#14]
`prop-types.js` and `prop-types.min.js` are build artifacts and thus it doesn't really make sense for them to be committed to source control. Having them in source control makes diffs messier, unnecessarily bloats out the repository, and makes it easy for someone to forget to update them. They should be in the `.gitignore`.

**Comment by claydiffrient** [comment]
Aren't they required to be there for unpkg.com to work properly?

Well... I guess they just need to be published to npm so they could be .gitignore'd since they are already in the `"files"` whitelist for the package.json.

**Comment by Daniel15** [comment]
> Aren't they required to be there for unpkg.com to work properly?

No, because unpkg reads from npm packages. https://unpkg.com/babel-standalone/babel.js works even though the file is `.gitignore`'d.

**Comment by aweary** [comment]
This was resolved by https://github.com/reactjs/prop-types/pull/13
