### ISSUE TITLE
Remove unused code from production build

### ISSUE THREAD

**Issue by aweary** [reactjs/prop-types#16]
See https://github.com/facebook/react/issues/9398

> Can we remove junk code from PropTypes prod build? It doesn't use bundle-collapser so it ships all those method names (e.g. “fbjs/lib/invariant”). This is fixable if you add “-p bundle-collapser/plugin” to browserify call. Additionally, there seems to be some junk invariant() code which is easy to fix if we just turn this into an inlined error. https://unpkg.com/prop-types@15.5.6/prop-types.min.js

**Comment by gaearon** [comment]
Want to help? @aweary

**Comment by aweary** [comment]
@gaearon happy to!

**Comment by aweary** [comment]
Resolved by https://github.com/reactjs/prop-types/pull/20
