### ISSUE TITLE
Context around the change

### ISSUE THREAD

**Issue by hozefaj** [reactjs/prop-types#21]
Other than the fact mentioned on the [blog](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes) `We've extracted the built-in prop types to a separate package to reflect the fact that not everybody uses them.` is there any other use of moving it to separate module?

**Comment by gaearon** [comment]
There are a few reasons:

* Indeed, some people don't use them.
* Issues and discussions are largely unrelated to React, and better live in a separate repo.
* It is less hassle for React alternatives like Preact and Inferno to consume components defined using React if they explicitly import a separate library for PropTypes.
* We don’t want to “get in the way” of a better PropTypes-like abstraction if one comes along. We think removing “blessed” status of PropTypes might encourage some movement in this area, especially if we loosen up the API contract a little bit in future releases.

Hope this helps!

**Comment by hozefaj** [comment]
Thanks for the info. Always helps to get context.
