### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by mannyreds11** [reactjs/prop-types#22]
I keep getting warning errors when running my jest tests after updating to prop-types package:

```
PASS  __tests__/pages/about.test.js
  ● Console

    console.error node_modules/fbjs/lib/warning.js:36
      Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

package.json:

```
"dependencies": {
    "babel-eslint": "^7.2.1",
    "contentful": "^4.1.2",
    "csso": "^3.0.1",
    "element-class": "^0.2.2",
    "es6-promise": "^4.1.0",
    "eslint": "^3.18.0",
    "eslint-config-airbnb": "^14.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^4.0.0",
    "eslint-plugin-react": "^6.10.3",
    "isomorphic-fetch": "^2.2.1",
    "lodash.camelcase": "^4.3.0",
    "lodash.merge": "^4.6.0",
    "memory-cache": "^0.1.6",
    "next": "^2.1.1",
    "randomstring": "^1.1.5"
  },
  "devDependencies": {
    "babel-jest ": "^19.0.0",
    "babel-plugin-transform-define": "^1.2.0",
    "babel-preset-es2015": "^6.24.0",
    "bunyan": "^1.8.10",
    "enzyme": "^2.8.0",
    "jest": "^19.0.2",
    "jest-cli": "^19.0.2",
    "lighthouse": "^1.6.3",
    "prop-types": "^15.5.6",
    "react": "^15.4.2",
    "react-addons-test-utils": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-markdown": "^2.4.6",
    "react-test-renderer": "^15.4.2",
    "sinon": "^2.1.0"
  },
```

About.js:

```
import React, { Component } from 'react';
import PropTypes from 'prop-types';
```

Tried upgrading "react",  "react-addons-test-utils", "react-dom" and "react-test-renderer" to 15.5.1 - Didn't work
Tried upgrading "react",  "react-addons-test-utils", "react-dom" to 15.5.3 - Didn't work

Any help would be appreciated. Thanks

**Comment by JayAndCatchFire** [comment]
Are you using any third-party react components in the components that you're testing?

**Comment by gaearon** [comment]
It is likely coming from your dependencies. Please give them time to update, it's barely been a few days. You will likely see the warnings go away in a month or two. By this time we'll hopefully get React 16 out and your code will be ready to upgrade!

**Comment by DimitarChristoff** [comment]
it should probably only fire warning when `NODE_ENV=development` - not test/production

**Comment by spmebrge** [comment]
^^ In addition to seeing these fire off when `NODE_ENV-development` I am also seeing them when `NODE_ENV=test`

**Comment by comerc** [comment]
Solution for TypeScript

change:
```
import * as React from 'react' 
```

to:
```
import React from 'react' 
```

**Comment by fivepointseven** [comment]
I'm having the same issue because I want to access Flow types and this requires the `* as` in the import statement. Any way around this?
