### ISSUE TITLE
Does 'prop-types' also check the node_modules?

### ISSUE THREAD

**Issue by MichaelDeBoey** [reactjs/prop-types#24]
I've literally searched my whole (own) codebase for every `React.PropTypes` call and replaced them with the new `PropTypes` call, but I still get the warning.

Is it possible this is because of a dependency in my `node_modules` that's still using the `React.PropTypes` call?

**Comment by JayAndCatchFire** [comment]
That's very possible.  Are you using any dependencies that provide React components?

**Comment by gaearon** [comment]
Yes, absolutely, it is likely coming from dependencies. Please give packages to update, it's been just a few days. You will likely stop seeing this warning in a few months or so when all packages have updated. By that time we'll likely release React 16 and you'll be ready to switch!

**Comment by MichaelDeBoey** [comment]
OK thanks :-)
I thought the warnings could only come from my own codebase, so that's why I thought there was maybe something wrong... :-)

**Comment by gaearon** [comment]
They warn whenever `React.PropTypes` is accessed, no matter who does it. We can't tell if something is calling from your code or a library, but even if we could, if we only warned for your code you'd never know there are issues with libraries, and thus their authors wouldn't know to release updates. We encourage you to look at the stack trace in the warning and file an issue with the library in question.
