### ISSUE TITLE
process.env.NODE_ENV get replaced by 'development' in umd

### ISSUE THREAD

**Issue by elisherer** [reactjs/prop-types#31]
The process.env.NODE_ENV gets replaced by 'development' in umd

In file **prop-types/factoryWithTypeCheckers.js**: (line 148)
```js
  function createChainableTypeChecker(validate) {
    if (process.env.NODE_ENV !== 'production') {
      var manualPropTypeCallCache = {};
      var manualPropTypeWarningCount = 0;
    }
```

In umd bundle **prop-types.js**:
```js
  function createChainableTypeChecker(validate) {
    if ("development" !== 'production') {
      var manualPropTypeCallCache = {};
      var manualPropTypeWarningCount = 0;
    }
```

making the condition always true, is it by design or a bug?

**Comment by gaearon** [comment]
Yes, it is intentionally `true` in development (because it is checking for development environment).
For production, you want to use `prop-types.min.js` instead.
