### ISSUE TITLE
PropType validators error when an external lib bundles prop-types

### ISSUE THREAD

**Issue by OscarBarrett** [reactjs/prop-types#38]
If an external lib containing React components bundles `prop-types` the validators error is thrown when one of the components is used.

The solution (for webpack) is to add `prop-types` to `externals` in the webpack config and add it as a peerDependency.

This should probably be mentioned in the readme and/or in https://github.com/facebook/react/blob/master/docs/warnings/dont-call-proptypes.md

**Comment by gaearon** [comment]
Can you provide a standalone example demonstrating the issue? I don't fully understand what's going on.

**Comment by OscarBarrett** [comment]
I've created a simple example [here](https://github.com/OscarBarrett/prop-types-externals-example).

**Comment by gaearon** [comment]
I think the issue occurs because you're using a production build of the library with a development build of React.

**Comment by gaearon** [comment]
Fixed this in `prop-types@15.5.10`. If a library whose UMD build you're using updates, it should no longer be an issue. Thank you so much for the reproducible example—I wouldn't have fixed it so quickly otherwise.
